"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$kubernetes\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"

[kubernetes]
disabled = false
symbol = "⎈ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "bold blue"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "bold yellow"

[username]
show_always = false
format = "[$user]($style)@"

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold green"
